// The MC's sprite, cut into recolourable layers (Fase 10).
//
// Generated by scripts/build-character-layers.mjs — do not hand-edit the numbers.
// Re-run the script and paste its output if the segmentation changes.
//
// The whole point: every layer here is made of the ORIGINAL sprite's pixels, so
// the art style is not imitated, it is reused. Three earlier attempts drew the MC
// procedurally (rect lists, hand-authored string art, generated profiles) and all
// three read as cheap next to the source, because geometry does not reproduce a
// drawing.
//
// A layer carries two things beyond its image:
//
//   `stops`  — the luminance values, at percentiles of the layer's own pixels,
//              where each ramp entry sits. Percentiles and not equal bins: with
//              equal bins the cap's darkest anchor came out dark RED (its shadow
//              outnumbers its outline) and every recolour grew a red halo.
//   `source` — the sprite's own colour at each stop, so recolouring with this
//              exact ramp is a no-op and the identity render is the original.
//
// src/ui/characterDraw.ts remaps luminance onto a target ramp between the stops,
// which moves the hue and keeps the artist's shading.

// Layers are addressed by id everywhere: the asset key is `mc-layer-<id>` and the
// file is /assets/characters/layers/<id>.png.
export type LayerId =
  | "skin"
  | "hair"
  | "top"
  | "print"
  | "bottom"
  | "shoes"
  | "cap"
  | "brim"
  | "lens"
  | "frame"
  | "eyesOpen";

// Which palette ramp recolours a layer. Some roles are shared (lens and frame are
// both "glass") and three are fixed art that must not follow the outfit: the visor
// stays black, glass stays glass and an eye keeps its own colour.
export type LayerRole =
  | "skin"
  | "hair"
  | "top"
  | "print"
  | "bottom"
  | "shoes"
  | "cap"
  | "brim"
  | "glass"
  | "eye";

export interface CharacterLayer {
  id: LayerId;
  role: LayerRole;
  stops: readonly number[];
  source: readonly string[];
}

// The source sprite's own dimensions. Everything composites at this size and is
// scaled once, so no layer can drift out of register with another.
export const LAYER_SIZE = { w: 101, h: 240 } as const;

export const characterLayers: readonly CharacterLayer[] = [
  {
    id: "skin",
    role: "skin",
    stops: [0, 9.3, 82, 115.6, 255],
    source: ["#020104", "#1a0f14", "#7b441f", "#b26935", "#f0d2b8"],
  },
  {
    id: "hair",
    role: "hair",
    stops: [0, 30.4, 38.8, 40.5, 153.4],
    source: ["#060204", "#34150c", "#4a1e0f", "#532311", "#9f6d4f"],
  },
  {
    id: "top",
    role: "top",
    stops: [0, 4.9, 15.9, 19, 91.4],
    source: ["#010103", "#06060b", "#0f0f10", "#161515", "#344358"],
  },
  {
    id: "print",
    role: "print",
    stops: [76.4, 167, 223, 255, 255],
    source: ["#616060", "#a6a5a5", "#d7d7d7", "#fcfcfc", "#ffffff"],
  },
  {
    id: "bottom",
    role: "bottom",
    stops: [0, 15.9, 62.3, 82, 107.4],
    source: ["#010207", "#02183f", "#003c93", "#005ecb", "#0074e3"],
  },
  {
    id: "shoes",
    role: "shoes",
    stops: [0, 1.8, 13.7, 163, 255],
    source: ["#000000", "#040409", "#1c1b24", "#949392", "#f5f5f4"],
  },
  {
    id: "cap",
    role: "cap",
    stops: [0, 9.7, 53.7, 59.6, 255],
    source: ["#020109", "#2a0522", "#ac080b", "#d41719", "#f9e0df"],
  },
  {
    id: "brim",
    role: "brim",
    stops: [0, 0, 4.9, 10.2, 50.1],
    source: ["#000000", "#010000", "#060505", "#11100f", "#432713"],
  },
  {
    id: "lens",
    role: "glass",
    stops: [0, 28.2, 228, 248.2, 255],
    source: ["#050505", "#373736", "#cccccc", "#f7f7f6", "#fefefe"],
  },
  {
    id: "frame",
    role: "glass",
    stops: [0, 1, 30.2, 179.5, 255],
    source: ["#000000", "#060504", "#312c28", "#b6b7b5", "#f1f0f0"],
  },
  {
    id: "eyesOpen",
    // Its own role, not "glass": under the glass ramp the open eyes came out grey,
    // and an eye is not a lens.
    role: "eye",
    stops: [0, 14.2, 98.1, 216.7, 255],
    source: ["#010100", "#0e1f15", "#376a4c", "#c8cac4", "#f9f8f6"],
  },
];

// Bottom to top. The head stack is the part that matters: hair goes UNDER the cap
// (they are exclusive, but the order has to be right either way) and the eyes go
// last so nothing can bury them — the eyes are what make him a person.
export const layerOrder: readonly LayerId[] = [
  "skin",
  "bottom",
  "top",
  "print",
  "shoes",
  "hair",
  "cap",
  "brim",
  "lens",
  "frame",
  "eyesOpen",
];

export function layerById(id: LayerId): CharacterLayer {
  const found = characterLayers.find((layer) => layer.id === id);
  if (!found) throw new Error(`capa desconocida: ${id}`);
  return found;
}
